### ISSUE TITLE
Inclusive wording

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/ICC-Member-Website-Public#127]
## Feature

As part of continuous improvement, update messages to include both females and males members/customers by either:
- Using "he/she"
- Using "They"

## Task
- [ ] @iElsha gives strings to Tueri
- [ ] @Tueri makes the changes
- [ ] @iElsha update in code

**Comment by infinitypros** [comment]
@Tueri can you explain more about this issue so we know what are we looking on

**Comment by Tueri** [comment]
I have no idea, I assume just to change French default of male/female object wording to gender neutral English terms.
